from pathlib import Path
p=Path(r'C:\Users\carlo\Documents\PROYECTOS\CONTADORES\contabilidad-rs\.presentation-work\build_report.py')
s=p.read_text(encoding='utf-8')
s=s.replace('from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether','from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, Image as RLImage')
s=s.replace("OUT=r'C:\\Users\\carlo\\Documents\\PROYECTOS\\CONTADORES\\contabilidad-rs\\output\\pdf\\Invierte360_Informe_Diagnostico_y_Propuesta.pdf'", "OUT=r'C:\\Users\\carlo\\Documents\\PROYECTOS\\CONTADORES\\contabilidad-rs\\output\\pdf\\Invierte360_Informe_Diagnostico_y_Propuesta_Con_Marca.pdf'\nCOMPANY_LOGO=r'C:\\Users\\carlo\\Documents\\PROYECTOS\\CONTADORES\\contabilidad-rs\\.presentation-work\\brand\\invierte360.png'\nPERSONAL_LOGO=r'C:\\Users\\carlo\\Documents\\PROYECTOS\\CONTADORES\\contabilidad-rs\\.presentation-work\\brand\\carlos_lozano.png'")
s=s.replace("NAVY=colors.HexColor('#15334A'); TEAL=colors.HexColor('#148E89');", "NAVY=colors.HexColor('#15334A'); TEAL=colors.HexColor('#1D482B'); CORAL=colors.HexColor('#F2464E');")
s=s.replace("styles.add(ParagraphStyle(name='Labelx',fontName=BOLD,fontSize=7.3,textColor=TEAL,leading=9,spaceAfter=3))", "styles.add(ParagraphStyle(name='Labelx',fontName=BOLD,fontSize=7.3,textColor=TEAL,leading=9,spaceAfter=3))\nstyles.add(ParagraphStyle(name='HeaderWhite',fontName=BOLD,fontSize=7.3,textColor=WHITE,leading=9,spaceAfter=3))")
s=s.replace("c.saveState(); c.setStrokeColor(TEAL); c.setLineWidth(2); c.line(17*mm,h-15*mm,w-17*mm,h-15*mm)\n    c.setFont(BOLD,7); c.setFillColor(MUTED); c.drawString(17*mm,h-11*mm,'INVIERTE360  /  DIAGNÓSTICO Y ESTRATEGIA DIGITAL')", "c.saveState(); c.setStrokeColor(TEAL); c.setLineWidth(2); c.line(17*mm,h-15*mm,w-17*mm,h-15*mm)\n    c.drawImage(COMPANY_LOGO,17*mm,h-13*mm,width=8*mm,height=8*mm,mask='auto',preserveAspectRatio=True,anchor='c')\n    c.setFont(BOLD,7); c.setFillColor(MUTED); c.drawString(28*mm,h-11*mm,'INVIERTE360  /  DIAGNÓSTICO Y ESTRATEGIA DIGITAL')")
s=s.replace("data=[[P('EVIDENCIA','Labelx'),P('IMPACTO','Labelx'),P('SOLUCIÓN PROPUESTA','Labelx')],", "data=[[P('EVIDENCIA','HeaderWhite'),P('IMPACTO','HeaderWhite'),P('SOLUCIÓN PROPUESTA','HeaderWhite')],")
s=s.replace("('BACKGROUND',(0,0),(-1,0),PALE)", "('BACKGROUND',(0,0),(-1,0),NAVY)")
# Convert table column-heading cells to white text while retaining regular teal labels elsewhere.
for label in ['EVIDENCIA','QUÉ SIGNIFICA','ETAPA','PRIORIDAD','TRABAJO','ENTREGABLE','CONTENIDO']:
 s=s.replace(f"P('{label}','Labelx')",f"P('{label}','HeaderWhite')")
s=s.replace("story += [Spacer(1,44*mm),P('INVIERTE360  /  PROPUESTA DIGITAL','CoverLabel'),", "company_cell=Table([[RLImage(COMPANY_LOGO,width=20*mm,height=20*mm),P('INVIERTE360','H2x')]],colWidths=[24*mm,64*mm]); company_cell.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),0),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),0),('BOTTOMPADDING',(0,0),(-1,-1),0)]))\nbrand_row=Table([[company_cell,RLImage(PERSONAL_LOGO,width=22*mm,height=25.25*mm)]],colWidths=[121*mm,47*mm]); brand_row.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ALIGN',(1,0),(1,0),'RIGHT'),('LEFTPADDING',(0,0),(-1,-1),0),('RIGHTPADDING',(0,0),(-1,-1),0),('TOPPADDING',(0,0),(-1,-1),0),('BOTTOMPADDING',(0,0),(-1,-1),0)]))\nstory += [brand_row,Spacer(1,8*mm),P('DIAGNÓSTICO Y ESTRATEGIA DIGITAL','CoverLabel'),")
s=s.replace("price=Table([[P('INVERSIÓN DEL PAQUETE','Labelx')],[P('$100.000 CLP','Calloutx')]],colWidths=[168*mm]); price.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),PALE),('LINEBEFORE',(0,0),(0,-1),3,TEAL)", "price=Table([[P('INVERSIÓN DEL PAQUETE','Labelx')],[P('$100.000 CLP','Calloutx')]],colWidths=[168*mm]); styles['Calloutx'].textColor=CORAL; price.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),PALE),('LINEBEFORE',(0,0),(0,-1),3,CORAL)")
p.write_text(s,encoding='utf-8')
